### PR TITLE
Add a testutil class to be able to test formatters easily

### PR DESCRIPTION
**Pull request by Pierre-Sassoulas**
This will permit to reuse the code to assert that a formatter does something if activated or nothing if deactivated more easily.

### CODE REVIEW

**Comment by Pierre-Sassoulas** [comment]
Permit to do #25 's test with:
```python
def test_optional_formatters_argument(
    capsys: pytest.CaptureFixture[str],
    tmp_path: Path,
) -> None:
    """Test that an optional formatter is correctly turned on and off with arguments."""
    with FormatterAssert(
        '"""Summary. Body."""', [SplitSummaryAndDocstringFormatter()], capsys, tmp_path
    ) as asserter:
        asserter.assert_format_when_activated()
        asserter.assert_no_change_when_deactivated()
```

**Comment by DanielNoord** [comment]
Just two general comments:
1. I think we should make everything in `testutils` private with a leading underscore for now. (As long as we don't support plugins nobody would need it anyway).
2. Is there any use case for those properties outside of testing? If not I think it would be better to make them into utility functions within the testutils package. Not really a need to add functions to the codebase that are only necessary for testing imo.

**Comment by DanielNoord** [comment]
@Pierre-Sassoulas Have you had time to look at this?

**Comment by Pierre-Sassoulas** [comment]
No sorry I have a pretty busy week, it's on my radar though.

> if not I think it would be better to make them into utility functions within the testutils package. 

Did you mean a function inside `tests` ?

**Comment by DanielNoord** [comment]
> No sorry I have a pretty busy week, it's on my radar though.

No rush!

> > if not I think it would be better to make them into utility functions within the testutils package.
> 
> Did you mean a function inside `tests` ?

I think in `testutils`. Like: if we don't need those Class properties for the normal functionality of the program I think we shouldn't put them on the class (as they impact runtime of the program). So everything that is only necessary to test the program should be in `testutils` so it only impacts the running of the test suite instead of the actual runtime of the program.

**Comment by Pierre-Sassoulas** [comment]
Allright I understand.

>  Like: if we don't need those Class properties for the normal functionality of the program 

We could refactor the argparsing to use them (I did not do that yet.) Maybe we could do the refactor first ? what do you think ?

**Comment by DanielNoord** [comment]
> Allright I understand.
> 
> > Like: if we don't need those Class properties for the normal functionality of the program
> 
> We could refactor the argparsing to use them (I did not do that yet.) Maybe we could do the refactor first ? what do you think ?

Yeah makes sense. I'll do a final check of this PR > update the private names > merge and do a follow-up PR to `argparse`.

**Comment by DanielNoord** [comment]
Follow up in #37.

**Comment by Pierre-Sassoulas** [comment]
Thank you for finalizing this for me 😅

**Pull request merged**
