### PR TITLE
Run formatters based on the selected style

### PR DESCRIPTION
**Pull request by DanielNoord**

### CODE REVIEW

**Comment by DWesl** [comment]
With this framing, you could probably set the default for `--style` to `["default"]` and then append `"pep257"` if `len(self.namespace.styles) <= 1`

**Comment by DanielNoord** [comment]
Yeah I thought about that. However, if users did `--style=pep257` `default` would be missing so they would need to do `--style=pep257,default`, which doesn't seem right.
Adding `default` to `style` would also work, but this if check accomplishes the same and might be clearer? I don't know honestly 😄

**Comment by DWesl** [comment]
Depends on how the parser treats default values with `action="append"`.  I'd have to look into that to be sure.

**Comment by DanielNoord** [comment]
Yeah it just appends to the default. So you could end up with `["default", "pep257", "default"]`. That's not necessarily any issue I guess.

**Comment by DWesl** [comment]
> Yeah it just appends to the default. So you could end up with `["default", "pep257", "default"]`. That's not necessarily any issue I guess.

Since we're treating it as a set, not really.  If that bothers you, we could change the action to change the value to a `set` or `frozenset` when it's done parsing the command line.

**Pull request merged**
